# ====================================
# TERRAFORM / PROVIDER CONFIGURATION
# ====================================
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
provider "aws" {
  region = var.aws_region
}
# ====================================
# VPC RESOURCE
# ====================================
resource "aws_vpc" "capstone_vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = {
    Name        = "tlab12-capstone-vpc"
    Environment = "Production"
  }
}
# ====================================
# KMS KEY FOR LOG ENCRYPTION
# ====================================
data "aws_caller_identity" "current" {}

resource "aws_kms_key" "log_key" {
  description             = "KMS key for VPC Flow Logs CloudWatch Log Group"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "Enable IAM User Permissions"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
        }
        Action   = "kms:*"
        Resource = "*"
      },
      {
        Sid    = "Allow CloudWatch Logs Service"
        Effect = "Allow"
        Principal = {
          Service = "logs.${var.aws_region}.amazonaws.com"
        }
        Action = [
          "kms:Encrypt*",
          "kms:Decrypt*",
          "kms:ReEncrypt*",
          "kms:GenerateDataKey*",
          "kms:Describe*"
        ]
        Resource = "*"
        Condition = {
          ArnLike = {
            "kms:EncryptionContext:aws:logs:arn" = "arn:aws:logs:${var.aws_region}:${data.aws_caller_identity.current.account_id}:log-group:*"
          }
        }
      }
    ]
  })

  tags = {
    Name        = "tlab12-log-kms-key"
    Environment = "Production"
  }
}
# ====================================
# CLOUDWATCH LOG GROUP
# ====================================
resource "aws_cloudwatch_log_group" "vpc_flow_logs" {
  name              = "/aws/vpc/tlab12-flow-logs"
  retention_in_days = 7
  kms_key_id        = aws_kms_key.log_key.arn
  tags = {
    Name        = "tlab12-vpc-flow-logs"
    Environment = "Production"
  }
}
# ====================================
# IAM ROLE FOR VPC FLOW LOGS
# ====================================
resource "aws_iam_role" "vpc_flow_logs_role" {
  name = "tlab12-vpc-flow-logs-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "vpc-flow-logs.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })
  tags = {
    Name        = "tlab12-vpc-flow-logs-role"
    Environment = "Production"
  }
}
# ================================
# IAM POLICY FOR VPC FLOW LOGS
# ================================
# tfsec:ignore:aws-iam-no-policy-wildcards
resource "aws_iam_role_policy" "vpc_flow_logs_policy" {
  name = "tlab12-vpc-flow-logs-policy"
  role = aws_iam_role.vpc_flow_logs_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        # Wildcard required here because log stream names are dynamically generated by AWS VPC Flow Logs
        Resource = "${aws_cloudwatch_log_group.vpc_flow_logs.arn}:log-stream:*"
      },
      {
        Effect = "Allow"
        Action = [
          "logs:DescribeLogGroups",
          "logs:DescribeLogStreams"
        ]
        Resource = "*"
      }
    ]
  })
}
# ====================================
# VPC FLOW LOG
# ====================================
resource "aws_flow_log" "vpc_flow_logs" {
  vpc_id = aws_vpc.capstone_vpc.id
  traffic_type = "ALL"
  iam_role_arn    = aws_iam_role.vpc_flow_logs_role.arn
  log_destination = aws_cloudwatch_log_group.vpc_flow_logs.arn
  tags = {
    Name        = "tlab12-vpc-flow-logs"
    Environment = "Production"
  }
}
resource "aws_subnet" "public_subnet" {
  vpc_id                  = aws_vpc.capstone_vpc.id
  cidr_block              = "10.0.1.0/24"
  map_public_ip_on_launch = true
  availability_zone       = "${var.aws_region}a"
  tags = {
    Name = "tlab12-public-subnet"
  }
}
resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.capstone_vpc.id
  tags = {
    Name = "tlab12-igw"
  }
}
resource "aws_route_table" "public_rt" {
  vpc_id = aws_vpc.capstone_vpc.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.igw.id
  }
  tags = {
    Name = "tlab12-public-rt"
  }
}
resource "aws_route_table_association" "public_assoc" {
  subnet_id      = aws_subnet.public_subnet.id
  route_table_id = aws_route_table.public_rt.id
}
resource "aws_security_group" "web_sg" {
  name        = "tlab12-web-sg"
  description = "Security Group for Capstone Web Server with restricted access"
  vpc_id      = aws_vpc.capstone_vpc.id
  ingress {
    description = "Allow inbound HTTP traffic"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = [var.my_ip]
  }
  ingress {
    description = "Allow inbound SSH traffic"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.my_ip]
  }
  # tfsec:ignore:aws-ec2-no-public-egress-sgr
  egress {
    description = "Allow outbound HTTPS for package updates"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  # tfsec:ignore:aws-ec2-no-public-egress-sgr
  egress {
    description = "Allow outbound HTTP for package repositories"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    Name = "tlab12-web-sg"
  }
}
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }
}
resource "aws_instance" "web_server" {
  ami                    = data.aws_ami.amazon_linux_2023.id
  instance_type          = "t3.micro"
  subnet_id              = aws_subnet.public_subnet.id
  vpc_security_group_ids = [aws_security_group.web_sg.id]
  user_data = <<-EOF
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl start httpd
              systemctl enable httpd
              echo "<h1>🛡️ TLAB 12: Capstone Web Application Live!</h1><p>Deployed securely via Terraform & GitHub Actions.</p>" > /var/www/html/index.html
              EOF
  metadata_options {
    http_tokens = "required"
  }
  root_block_device {
    encrypted = true
  }
  tags = {
    Name = "tlab12-capstone-web-server"
  }
}
output "web_public_ip" {
  description = "Public IP of the deployed Web Server"
  value       = aws_instance.web_server.public_ip
}
output "web_url" {
  description = "Direct URL to access the web app"
  value       = "http://${aws_instance.web_server.public_ip}"
}